jwt:
  secret: 63fba97a41e0d004e10e8dbbcb9a547819280efb00a54c732aca36a8a58258e4fcc539ffc5159a7f0a7be78b86efe001c12ba6af6debeb0a89e8ce7e82e75455
  access:
    expiration: 3600 # access -> 1시간
    header: Authorization
  refresh:
    expiration: 1209600 # refresh -> 2주
    header: Authorization-refresh
  passwordTime:
    expiration: 180 # 3분
    header: Authorization-password